# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5

development:
  <<: *default
  timeout: 5000
  host: db
  port: 3306
  database: sys_dev
  username: root
  password: 123456
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false

test:
  <<: *default
  timeout: 5000
  host: db
  port: 3306
  database: sys_test
  username: root
  password: 123456
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false

staging:
  <<: *default
  timeout: 5000
  host: db
  port: 3306
  database: sys_staging
  username: root
  password: 123456
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false
