name: "Conventions"

on: [pull_request]

jobs:
  branch-naming-rules:
    name: Policy Branch Name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-zA-Z0-9\-])+'
          allowed_prefixes: 'master,staging,feature/,bugfix/,hotfix/,refactor/,doc/,dependabot/'
          ignore: master,develop
          min_length: 5
          max_length: 100